#pragma once
#define DEFAULT_TILE_SIZE_X 16
#define DEFAULT_TILE_SIZE_Y 16

#define WINDOW_WIDTH GRID_SIZE_PIXELS*17
#define WINDOW_HEIGHT GRID_SIZE_PIXELS*11
#define FRAMERATE 60

#define GRID_SIZE_PIXELS 64

#define PLAYER_WALK_SPEED 5
#define ENEMY_CHASE_SPEED 3

#define NUM_I_FRAMES 25