#pragma once
#define DEFAULT_TILE_SIZE_X 16
#define DEFAULT_TILE_SIZE_Y 16

#define WINDOW_WIDTH GRID_SIZE_PIXELS*12
#define WINDOW_HEIGHT GRID_SIZE_PIXELS*14
#define FRAMERATE 60

#define GRID_SIZE_PIXELS 64

#define PLAYER_SPEED 5
#define BULLET_SPEED 10
#define ENEMY_CHASE_SPEED 3

#define NUM_I_FRAMES 25

#define SCREEN_SCROLL_SPEED 1

#define BULLET_LIFE 25
#define FIELD_LIFE 60

#define ATTACK_COOLDOWN 15
#define SPECIAL_COOLDOWN 600